### ISSUE TITLE
OSError: [Errno 2] No such file or directory and others errors

### ISSUE THREAD

**Issue by patrickmaciel** [djl/vcprompt#34]
Today, when I update my Ubuntu 12.10 x64, I receive this message:

```
Traceback (most recent call last):
  File "/bin/vcprompt", line 672, in <module>
    prompt = main()
  File "/bin/vcprompt", line 226, in main
    output = vcprompt(options)
  File "/bin/vcprompt", line 179, in vcprompt
    conf = vcs(options)
  File "/bin/vcprompt", line 621, in svn
    process = Popen(command.split(), stdout=PIPE, stderr=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1259, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

My **prompt** is: PS1="\n\u@\h:\w \$(vcprompt -f '%b%m%u')\n> "

Anyway, thanks.

**Comment by djl** [comment]
Hmm. It looks like you don't have Subversion installed (or it's not in your `$PATH`). Are you sure you have Subversion installed?

In any case, a missing binary should not cause the entire thing to fall on it's face. I'll need to fix that.

**Comment by patrickmaciel** [comment]
It is just that! (I was embarrassed now)
Anyway, unfortunately I accessed the folder, which is an old project using SVN.

But currently only use the GIT.

Anyway thanks for the quick response.
