### ISSUE TITLE
suggestion: svn shows modified properties on 2nd column

### ISSUE THREAD

**Issue by maverickwoo** [djl/vcprompt#36]
From svn st --help:

Second column: Modifications of a file's or directory's properties
      ' ' no modifications
      'C' Conflicted
      'M' Modified

I realize it's debatable whether a changed property is a modification, but I lean towards calling it a modification since this indicates there is something in the working copy that should be checked-in.

**Comment by djl** [comment]
> I realize it's debatable whether a changed property is a modification, but I lean towards calling it a modification since this indicates there is something in the working copy that should be checked-in.

Yep, I'd agree with that.

I'd also add that any of these would also count as modified:

```
'D' Deleted
'R' Replaced
'!' item is missing (removed by non-svn command) or incomplete
```

And that `'A' Added` would qualify as "staged" (the `%a` token).

I'll look into adding this later.

**Comment by djl** [comment]
Updated the `%a` and `%m` handling in f1cf5416cab006d49ed83b08d258d39dbeefb690.

Thanks for the suggestion!
