### ISSUE TITLE
bzr repo with no modified [or untracked] file shows "unknown" in %m [or %u] in git:bdf72ca

### ISSUE THREAD

**Issue by maverickwoo** [djl/vcprompt#41]
In line 249 both modified and untracked are initialized as options.unknown. But they never get overwritten if the repo has no modifications and no untracked files. These two variables should have a default value of the empty string, and only be set to options.unknown if returncode != 0.

**Comment by djl** [comment]
Fixed in 755fed41ef293285dd39f9f17bdec31129d8e9d3.

This bug has been around for quite a while I'm surprised nobody caught it until now.
