### ISSUE TITLE
HTTPS redirect breaks Curl request

### ISSUE THREAD

**Issue by bshaffer** [djl/vcprompt#8]
The README should be updated to https://github.com/xvzf/vcprompt/raw/master/bin/vcprompt for the curl example.  The difference is the "https" protocol.  Otherwise, curl gives you this:

```
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/0.7.67</center>
</body>
</html>
```

**Comment by djl** [comment]
Fixed in 68fa557c3aefcfdb2181562a6f3bc1ca7a5a3e48.

Thanks!
